name: frontend-pipeline nextjs workflow

on:
  push:
    branches:
      - main 
      - release/*
    paths-ignore:
      - '**/README.md'
      - '**/*.md'
      - '**/*.txt'
      - '**/*.log'
      - '**/.gitignore'
      - '**/.dockerignore'
      - '**/LICENSE'
      - '**/*.lock'
  pull_request:
    branches:
      - main 
      - release/*
  workflow_dispatch:
    inputs:
      ask_for_approval:
        description: "Do you want to proceed with the deployment?"
        required: true
        default: "no"
        type: choice 
        options:
          - "yes"
          - "no"

jobs:
  deploy_front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Setup EC2 and Deploy
        run: |
          ssh -i ~/.ssh/ec2_key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'ENDSSH'
          set -e
          
          echo "=========================================="
          echo "Setting up Next.js on EC2"
          echo "=========================================="
          
          # Update system packages
          echo "[1/9] Updating system packages..."
          sudo apt update && sudo apt upgrade -y
          
          # Install required dependencies
          echo "[2/9] Installing system dependencies..."
          sudo apt install -y curl git build-essential nginx
          
          # Install Node.js 18 via NodeSource
          echo "[3/9] Installing Node.js 18..."
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt install -y nodejs
          fi
          echo "Node.js version: $(node -v)"
          echo "npm version: $(npm -v)"
          
          # Install PM2 globally
          echo "[4/9] Installing PM2..."
          sudo npm install -g pm2
          
          # Setup PM2 to start on boot
          sudo pm2 startup systemd -u $USER --hp $HOME || true
          
          # Create app directory
          echo "[5/9] Setting up app directory..."
          APP_DIR="/var/www/nextjs-app"
          sudo mkdir -p $APP_DIR
          sudo chown -R $USER:$USER $APP_DIR
          cd $APP_DIR
          
          # Clone or pull repository
          echo "[6/9] Fetching latest code..."
          if [ -d ".git" ]; then
            git pull origin main
          else
            git clone ${{ secrets.REPO_URL }} . || echo "Please set REPO_URL secret"
          fi
          
          # Setup environment variables
          echo "[7/9] Setting up environment variables..."
          cat > .env << 'ENVEOF'
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_ANALYTICS_ID=${{ secrets.NEXT_PUBLIC_ANALYTICS_ID }}
          NEXT_PUBLIC_SOCKET_URL=${{ secrets.NEXT_SOCKET_URL }}
          NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
          ENVEOF
          
          # Install dependencies and build
          echo "[8/9] Installing dependencies and building..."
          npm install --legacy-peer-deps
          npm install sharp --legacy-peer-deps
          npm run build
          
          # Deploy with PM2
          echo "[9/9] Deploying application..."
          pm2 delete nextjs-app 2>/dev/null || true
          pm2 start npm --name "nextjs-app" -- start
          pm2 save
          
          # Setup Nginx reverse proxy
          sudo tee /etc/nginx/sites-available/nextjs << 'NGINXEOF'
          server {
              listen 80;
              server_name _;
              
              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_cache_bypass $http_upgrade;
              }
          }
          NGINXEOF
          
          sudo ln -sf /etc/nginx/sites-available/nextjs /etc/nginx/sites-enabled/
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo nginx -t && sudo systemctl reload nginx
          
          echo ""
          echo "=========================================="
          echo "Deployment Complete!"
          echo "App running at http://${{ secrets.EC2_HOST }}"
          echo "=========================================="
          ENDSSH

      - name: Cleanup SSH key
        if: always()
        run: rm -rf ~/.ssh/ec2_key